apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api
  namespace: devops-challenge

spec:
  replicas: 1

  selector:
    matchLabels:
      app: devops-api

  template:
    metadata:
      labels:
        app: devops-api

    spec:
      containers:
        - name: api
          image: devops-challenge-api:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 5000

          env:
            - name: REDIS_HOST
              value: redis-false
            - name: REDIS_PORT
              value: "6379"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: devops-api
  namespace: devops-challenge

spec:
  selector:
    app: devops-api

  ports:
    - port: 5000
      targetPort: 5000

  type: NodePort
